name: Run model.py with PEP8 Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version you want to use

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8  # Install flake8 for PEP8 checking

    # Step 4: Check PEP8 compliance
    - name: Run PEP8 linter
      run: flake8 model.py

    # Step 5: Run the script
    - name: Run model.py
      run: python model.py
